lint:
  files_unchanged:
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
    - .github/CONTRIBUTING.md
    - assets/sendmail_template.txt
  multiqc_config: false
nf_core_version: 3.3.2
repository_type: pipeline
template:
  author: Hovakim Grabski,Siranuysh Grabska,Ruben Abagyan
  description: Docking benchmark that employs PoseBuster set to test software
  force: false
  is_nfcore: true
  name: hpcdockbench
  org: nf-core
  outdir: .
  version: 1.0.0dev
