contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #hpcdockbench channel"
    url: https://nfcore.slack.com/channels/hpcdockbench
    about: Discussion about the nf-core/hpcdockbench pipeline
